feat: New command - create-dev-account
near/cargo-near pull request #108
Opened 2023-10-08 08:56 UTC by FroVolod

Resolves #106

2023-10-09 10:36 UTC, frol commented on cargo-near/src/commands/create_dev_account/mod.rs
> +    /// I would like to create a random account
```suggestion
        message = "use-random-account-id     - I would like to create a random account (useful for quick start development)"
    ))]
    /// Use a random name for account (useful for quick start development)
```

2023-10-19 10:25 UTC, frol requested changes

2023-10-19 10:25 UTC, frol commented on cargo-near/src/commands/abi_command/mod.rs
>      ) -> color_eyre::eyre::Result<Option<crate::types::utf8_path_buf::Utf8PathBufInner>> {
I believe these can be removed

2023-10-19 10:25 UTC, frol commented on cargo-near/src/commands/build_command/mod.rs
>      ) -> color_eyre::eyre::Result<Option<crate::types::utf8_path_buf::Utf8PathBufInner>> {
Probably need to remove these as well

2023-10-19 10:31 UTC, FroVolod commented on cargo-near/src/commands/abi_command/mod.rs
>      ) -> color_eyre::eyre::Result<Option<crate::types::utf8_path_buf::Utf8PathBufInner>> {
Done

2023-10-19 10:35 UTC, FroVolod commented on cargo-near/src/commands/build_command/mod.rs
>      ) -> color_eyre::eyre::Result<Option<crate::types::utf8_path_buf::Utf8PathBufInner>> {
Done

2023-10-19 10:51 UTC, frol approved these changes

2023-10-19 11:03 UTC, merged