test: add docker build integration test
near/cargo-near pull request #169
Opened 2024-07-03 17:03 UTC by dj8yfo

2024-07-03 22:19 UTC, Canvinus approved these changes

2024-07-05 10:37 UTC, frol requested changes

2024-07-05 10:37 UTC, frol commented on cargo-near/src/commands/build_command/docker.rs
> +                log::info!("input device is a tty: {}", atty::is(atty::Stream::Stdin));
Should it be removed or at least downgraded to debug?

2024-07-05 10:37 UTC, frol commented on integration-tests/tests/abi/borsh_schema.rs
> +    log::warn!("path {:?}", std::env::args().collect::<Vec<_>>());
Please, refactor as discussed offline

2024-07-05 15:03 UTC, frol approved these changes

2024-07-05 15:03 UTC, merged