feat: allow `--no-locked` for build, forbid for deploy; doc/guidance
near/cargo-near pull request #174
Opened 2024-07-08 21:31 UTC by dj8yfo

- **chore: increase visibility of git dirty warning**
- **doc: update per target behaviour**

2024-07-09 12:27 UTC, dj8yfo commented
@race-of-sloths, please include my PR in the race

2024-07-09 12:28 UTC, race-of-sloths commented
@dj8yfo Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
New Sloth joined the Race! Welcome!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/dj8yfo?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/dj8yfo?type=bot&theme=light">
    <img alt="Shows profile picture for the author of the PR" src="https://badge.race-of-sloths.com/dj8yfo?type=bot&theme=white">
</picture>](https://race-of-sloths.com/profile/dj8yfo)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/dj8yfo)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

2024-07-09 12:29 UTC, dj8yfo commented
@race-of-sloths score 1

2024-07-09 12:29 UTC, race-of-sloths commented
### ❌ Self-scoring is not permitted. 
Let's keep it fair! 👍

2024-07-09 13:02 UTC, frol commented
@race-of-sloths score 1

2024-07-09 13:03 UTC, race-of-sloths commented
### 🌟 Score recorded!

@frol, thank you for scoring this pull request in the Race of Sloths!

2024-07-10 23:12 UTC, frol requested changes
Overall looks good to me, but please, address the review comments

2024-07-10 23:12 UTC, frol commented on README.md
> +
This sounds like we discourage `cargo near build` and even moved it upfront. This is not the right message to deliver. Please, make it less aggressive and prominent

2024-07-10 23:12 UTC, frol commented on README.md
> +  - such builds are considered effectively DEMO-mode
Before this feature, we had 4 years of NEAR living just fine with non-reproducible builds, let's not discourage it too much. Such contracts are still valid contracts and can hold millions $ in assets.

```suggestion
```

2024-07-10 23:12 UTC, frol commented on cargo-near/src/commands/build_command/docker.rs
> +    );
```suggestion
```

2024-07-11 13:22 UTC, merged

2024-07-11 13:23 UTC, race-of-sloths commented
### 🌟 Score recorded!

@frol, thank you for scoring this pull request in the Race of Sloths!

2024-07-12 13:42 UTC, race-of-sloths commented
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 5!
You have received 50 Sloth points for this contribution