feat: `env` flag for external parameters of docker build and regular build
near/cargo-near pull request #226
Opened 2024-09-19 19:42 UTC by dj8yfo

- **chore: add `--env` argument to cargo near build/deploy commands**
- **chore: update `interactive-clap` revision in Cargo.lock (patched from git version)**
- **chore: add `env` argument to `cargo_near_build::near::abi::generate` function**
- **chore: update `interactive-clap` from crates.io**
- **feat: use external `env` field in `cargo_near_build::near::build::run` function**
- **chore: add `env` flags to command export in `build::input::Opts::get_cli_build_command` in lib run variant**
- **feat: add support of `--env` flag in docker build without cmd in manifest**
- **chore: split `metadata::ReproducibleBuild::validate`**
- **chore: add optional `passed_env` to toml manifest metadata for reproducible builds**
- **feat: add arguments from `passed_env` in toml to cmd in docker**
- **chore: update `near new` template with added `passed_env` manifest field**

2024-09-20 17:42 UTC, dj8yfo commented
@race-of-sloths ping

2024-09-20 17:43 UTC, race-of-sloths commented
@dj8yfo Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!


[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/dj8yfo?type=bot&pr=near/cargo-near/226&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/dj8yfo?type=bot&pr=near/cargo-near/226&theme=light">
    <img alt="Shows profile picture for the author of the PR" src="https://badge.race-of-sloths.com/dj8yfo?type=bot&pr=near/cargo-near/226&theme=white">
</picture>](https://race-of-sloths.com/profile/dj8yfo)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command. Alternatively, autoscoring [1,2] will be applied for this pull request

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/dj8yfo)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

2024-09-23 10:24 UTC, frol requested changes
Feel free to ignore `nit` comments, but there is one that is important

2024-09-23 10:24 UTC, frol commented on cargo-near-build/src/types/near/build/input/docker_context.rs
> +                }).flat_map(|env_key| {
nit: It is really hard to reason about. Simple `if let` would be far easier to read, IMO

2024-09-23 10:24 UTC, frol commented on cargo-near-build/src/types/near/build/input/docker_context.rs
> +        );
nit: I think `if let` would be easier in this case

2024-09-23 10:24 UTC, frol commented on cargo-near-build/src/types/near/build/input/mod.rs
> +        equal_pairs.iter().for_each(|equal_pair| {
nit: I find simple `for` loop easier to read than `iter().for_each() + closure`

2024-09-23 11:39 UTC, dj8yfo commented on cargo-near/src/commands/new/new-project-template/Cargo.toml.template
> +passed_env = []
resolved by https://github.com/near/cargo-near/pull/226/commits/99c3be15af939c61bff63f833e6ba82b1af7c0ef

2024-09-23 12:44 UTC, dj8yfo commented on cargo-near-build/src/near/build/mod.rs
> +    };
removed nesting , but `concat` would require additional `collect`, and there's one more extend, that will be needed in one of the following prs

2024-09-23 12:57 UTC, dj8yfo commented on cargo-near-build/src/near/docker_build/subprocess_step.rs
> +            shell_words::join(cargo_cmd)
renamed to `shell_escaped_cargo_cmd` . not possible to move to 84 due to blocks nesting and borrowing of `String` to `&str`

2024-09-24 11:23 UTC, dj8yfo commented on cargo-near-build/src/types/near/build/input/docker_context.rs
> +        manifest_command.map_or_else(
i beleive the size is the same, but `if let Some()` is met more often and therefore is easier to understand

2024-09-24 13:50 UTC, frol approved these changes
@race-of-sloths score 8

2024-09-24 13:50 UTC, merged